name: CI/CD Pipeline

on: 
  push: 
    branches:
      - master

jobs:
  test:
    name: CI Pipeline
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: TestProject Execute Jobs
        uses: Mahan-F/test-project-action@v1.1.1
        with:
          project_id: ${{ secrets.TEST_PROJECT_ID }}
          api_key: ${{ secrets.TEST_PROJECT_API_KEY }}
